version: "3.9"

networks:
  searchengine_network:
    driver: overlay

services:
  api:
    image: searchengine-baseline-api:latest
    deploy:
      replicas: 3
    volumes:
      - C:\Users\emil_\data-searchengine:/data:ro
    ports:
      - 8040:80
    networks:
      - searchengine_network

  web:
    image: searchengine-baseline-web:latest
    deploy:
      replicas: 1
    ports:
      - 8080:80
    networks:
      - searchengine_network

  loadbalancer:
    image: searchengine-baseline-loadbalancer:latest
    deploy:
      replicas: 1
    ports:
      - 8020:80
    networks:
      - searchengine_network
    depends_on:
      - api
      - web
